ALTER TYPE "MatchSessionCasualtyResolutionType" ADD VALUE IF NOT EXISTS 'SERIOUS_INJURY';
ALTER TYPE "MatchSessionCasualtyResolutionType" ADD VALUE IF NOT EXISTS 'LASTING_INJURY_ARMOUR';
ALTER TYPE "MatchSessionCasualtyResolutionType" ADD VALUE IF NOT EXISTS 'LASTING_INJURY_MOVEMENT';
ALTER TYPE "MatchSessionCasualtyResolutionType" ADD VALUE IF NOT EXISTS 'LASTING_INJURY_PASSING';
ALTER TYPE "MatchSessionCasualtyResolutionType" ADD VALUE IF NOT EXISTS 'LASTING_INJURY_AGILITY';
ALTER TYPE "MatchSessionCasualtyResolutionType" ADD VALUE IF NOT EXISTS 'LASTING_INJURY_STRENGTH';
ALTER TYPE "MatchSessionCasualtyResolutionType" ADD VALUE IF NOT EXISTS 'DEAD';

ALTER TABLE "TeamPlayer"
ADD COLUMN "isDead" BOOLEAN NOT NULL DEFAULT false;
